spring.application.name=dms

#----- MySQL Database Connection -----

#server.port=${PORT:8080}
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}
#spring.jpa.hibernate.ddl-auto=update


#----- Local MySQL Database Connection -----

# The JDBC URL for your database
spring.datasource.url=jdbc:mysql://localhost:3306/DMS_DIRECTORY?useSSL=false&serverTimezone=UTC&characterEncoding=utf8

# The username and password for the database
spring.datasource.username=springstudent
spring.datasource.password=SpringStudent@14$

# The MySQL driver class (optional in modern Spring Boot, but good practice to include)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# (optional) see why JPA fails
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.SQL=INFO

# Because your tables/cols include reserved or uppercase names (e.g., USER, ROLE)
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# 32+ byte secret recommended. Put real secret in env/Render Secret.
#app.jwt.access-secret=change-me-32b-minimum-access-key-change-me
#app.jwt.refresh-secret=change-me-32b-minimum-refresh-key-change
app.jwt.access-secret=0123456789abcdefghijklmnopqrstuvwxyzAB
app.jwt.refresh-secret=ZYXWVUTSRQPONMLKJIHGFEDCBA9876543210
app.jwt.access-expiration-ms=900000
app.jwt.refresh-expiration-ms=1209600000















