spring.application.name=dms

#----- MySQL Database Connection -----

# The JDBC URL for your database
#spring.datasource.url=jdbc:mysql://localhost:3306/DMS_DIRECTORY

# The username and password for the database
#spring.datasource.username=springstudent
#spring.datasource.password=SpringStudent@14$

# The MySQL driver class (optional in modern Spring Boot, but good practice to include)
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update







