spring.application.name=dms

#----- Database Connection -----
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/DMS_DIRECTORY?useSSL=false&serverTimezone=UTC&characterEncoding=utf8}
spring.datasource.username=${DB_USER:springstudent}
spring.datasource.password=${DB_PASS:SpringStudent@14$}

# JPA/Hibernate Configuration - CHANGED THIS LINE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# Logging Configuration
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
#logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc=DEBUG

# JWT Configuration
app.jwt.access-secret=${SECRET_ACCESS:0123456789abcdefghijklmnopqrstuvwxyzAB}
app.jwt.refresh-secret=${REFRESH_SECRET:ZYXWVUTSRQPONMLKJIHGFEDCBA9876543210}
app.jwt.access-expiration-ms=${ACCESS_EXP:3600000}
app.jwt.refresh-expiration-ms=${REFRESH_EXP:1209600000}

# Server port
server.port=${PORT:8080}
# Add these lines temporarily
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE